[phases.setup]
commands = [
  "echo 'Setup phase'"
]

[phases.install]
commands = [
  # Instala dependências PHP e Node
  "composer install --no-dev --optimize-autoloader",
  "npm install"
]

[phases.build]
commands = [
  # Compila assets com Vite
  "npm run build"
]

[phases.start]
commands = [
  # Roda migrations automaticamente
  "php artisan migrate --force",
  # Inicia Laravel na porta do Railway
  "php artisan serve --host 0.0.0.0 --port $8080"
]

[phases.predeploy]
commands = [
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]
