[phases.setup]
commands = [
  "echo 'Setup phase'"
]

[phases.install]
commands = [
  "composer install --no-dev --optimize-autoloader",
  "npm install"
]

[phases.build]
commands = [
  "npm run build" # ou npm run prod dependendo do seu setup
]

[phases.start]
commands = [
  # start Laravel
  "php artisan migrate --force",
  "php artisan serve --host 0.0.0.0 --port $PORT"
]
